### PR TITLE
fs: properly handle ENOTSUP in copyXAttrs

### LINKED ISSUE #244: [Bug] CopyDir fails on systems without xattr support
The [CopyDir()](https://github.com/containerd/continuity/blob/50fa7de4fc5d1529fed1c4d6e3efad231bf5a232/fs/copy.go#L74) call will fail on filesystems that do not support extended attributes. This is because the function will eventually call [sysx.LListxattr()](https://github.com/containerd/continuity/blob/50fa7de4fc5d1529fed1c4d6e3efad231bf5a232/fs/copy_linux.go#L65), which will return ENOTSUP. This shouldn't be a problem for normal operations, as it just means there are no xattrs to copy, but as it's still an error it will say the function call failed.

This can be mitigated by attaching an XAttrErrorHandler to the CopyDir function call, but this being default behavior seems to be a bug.

### PR DESCRIPTION
**Pull request by sondavidb**
Fixes #244. More context in the issue.

Filesystems without xattr support do not have any xattrs to copy. The syscall for this will return ENOTSUP to indicate this, but continuity will treat it as a regular error. This change will return nil if this call returns ENOTSUP.

### CODE REVIEW

**Review by estesp — APPROVED** [review]
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

File: fs/copy_linux.go [hunk 1]
```diff
@@ -64,6 +64,9 @@ func copyFileInfo(fi os.FileInfo, src, name string) error {
 func copyXAttrs(dst, src string, excludes map[string]struct{}, errorHandler XAttrErrorHandler) error {
 	xattrKeys, err := sysx.LListxattr(src)
 	if err != nil {
+		if err == unix.ENOTSUP {
```
Comment (thaJeztah) [inline fs/copy_linux.go:67]: Oh! Actually; this is handling an error returned by `sysx`,  which is not a raw stdlib / syscall package, perhaps better to use `errors.Is()` here?

Some discussion with @robmry and @djs55 (we happened to be looking into a similar issue), and there's some discussion if `EOPNOTSUPP` should be handled here; this was related to https://elixir.bootlin.com/linux/v6.10/source/fs/fuse/xattr.c#L23

Comment (sondavidb) [reply fs/copy_linux.go]: > perhaps better to use errors.Is() here

Makes sense, pushed the change

> there's some discussion if `EOPNOTSUPP` should be handled here

It seems pretty reasonable to me, since the `fuse_getxattr` call would also fail in this use case. LMK and I can add add a check for this condition

**Comment by estesp** [comment]
haven't had time to look deeper, but this CI test failure is strange; I don't think we have flakes in this project, so is this being caused by the change:
```
=== RUN   TestDiffDirChangeWithOverlayfs
    diff_test.go:249: failed diff dir change: Unexpected number of changes:
        got(5):
        	modify	/dir1
        	delete	/dir1/d
        	modify	/dir1/f
        	modify	/dir2/d/f
        	delete	/dir3/.wh..opq
        expected(8):
        	modify	/dir1
        	delete	/dir1/d
        	modify	/dir1/f
        	modify	/dir2
        	modify	/dir2/d
        	modify	/dir2/d/f
        	modify	/dir3
        	delete	/dir3/.wh..opq
--- FAIL: TestDiffDirChangeWithOverlayfs (0.00s)
```

**Comment by thaJeztah** [comment]
@estesp I think I saw the same failure on https://github.com/containerd/continuity/pull/242

wondering if it's changes on the runners

**Comment by AkihiroSuda** [comment]
Please rebase to pass the CI
